config/routes.rb
Rails.application.routes.draw do

  resources :file_importeds
  devise_scope :user do
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
    unauthenticated do
      root 'devise/sessions#new'
    end
    authenticated do
      root 'home#index', as: :authenticated_root
      resources :contacts do
        collection { post :import_csv }
      end
    end
  end
end

app/models/file_imported.rb
class FileImported < ApplicationRecord
  belongs_to :user
end

app/controllers/file_importeds_controller.rb
class FileImportedsController < ApplicationController
  before_action :set_file_imported, only: %i[ show edit update destroy ]

  # GET /file_importeds or /file_importeds.json
  def index
    @file_importeds = FileImported.all
  end

  # GET /file_importeds/1 or /file_importeds/1.json
  def show
  end

  # GET /file_importeds/new
  def new
    @file_imported = FileImported.new
  end

  # GET /file_importeds/1/edit
  def edit
  end

  # POST /file_importeds or /file_importeds.json
  def create
    @file_imported = FileImported.new(file_imported_params)

    respond_to do |format|
      if @file_imported.save
        format.html { redirect_to @file_imported, notice: "File imported was successfully created." }
        format.json { render :show, status: :created, location: @file_imported }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @file_imported.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /file_importeds/1 or /file_importeds/1.json
  def update
    respond_to do |format|
      if @file_imported.update(file_imported_params)
        format.html { redirect_to @file_imported, notice: "File imported was successfully updated." }
        format.json { render :show, status: :ok, location: @file_imported }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @file_imported.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /file_importeds/1 or /file_importeds/1.json
  def destroy
    @file_imported.destroy
    respond_to do |format|
      format.html { redirect_to file_importeds_url, notice: "File imported was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_imported
      @file_imported = FileImported.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def file_imported_params
      params.require(:file_imported).permit(:filename, :status, :user_id)
    end
end

app/helpers/file_importeds_helper.rb
module FileImportedsHelper
end

app/views/file_importeds/_form.html.erb
<%= form_with(model: file_imported) do |form| %>
  <% if file_imported.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(file_imported.errors.count, "error") %> prohibited this file_imported from being saved:</h2>

      <ul>
        <% file_imported.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :filename %>
    <%= form.text_field :filename %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/file_importeds/_headers_match.html.erb
<div class="container pt-4">
  <% if @headers %>
    <br>
    <h4> Please match the column headers </h4>
    <br>
    <%= form_tag(import_csv_contacts_url, multipart: true, method: :post) do %>
      <%= label_tag 'Name Header' %>
      <%= select_tag :name_header, options_for_select(@headers) %>
      <br>
      <%= label_tag 'Birthdate Header' %>
      <%= select_tag :birthdate_header, options_for_select(@headers) %>
      <br>
      <%= label_tag 'Phone Header' %>
      <%= select_tag :phone_header, options_for_select(@headers) %>
      <br>
      <%= label_tag 'Address Header' %>
      <%= select_tag :address_header, options_for_select(@headers) %>
      <br>
      <%= label_tag 'Credit Card Header' %>
      <%= select_tag :credit_card_header, options_for_select(@headers) %>
      <br>
      <%= label_tag 'Email Header' %>
      <%= select_tag :email_header, options_for_select(@headers) %>
      <br>
      <%= hidden_field_tag :attachment, @file_path %>
      <br>
      <label class="btn btn-secondary btn-file">
        Select again CSV File
        <%= file_field_tag :attachment %>
      </label>
      <%= submit_tag("Submit") %>
    <% end %>


  <% end %>
</div>

app/views/file_importeds/edit.html.erb
<h1>Editing File Imported</h1>

<%= render 'form', file_imported: @file_imported %>

<%= link_to 'Show', @file_imported %> |
<%= link_to 'Back', file_importeds_path %>

app/views/file_importeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>File Importeds</h1>

<table class="table">
  <thead>
    <tr>
      <th>Filename</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @file_importeds.each do |file_imported| %>
      <tr>
        <td><%= file_imported.filename %></td>
        <td><%= file_imported.status %></td>
        <td><%= link_to 'Show', file_imported %></td>
        <td><%= link_to 'Edit', edit_file_imported_path(file_imported) %></td>
        <td><%= link_to 'Destroy', file_imported, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/file_importeds/new.html.erb
<h1>New File Imported</h1>

<%= render 'form', file_imported: @file_imported %>

<%= link_to 'Back', file_importeds_path %>

app/views/file_importeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @file_imported.filename %>
</p>

<p>
  <strong>Status:</strong>
  <%= @file_imported.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @file_imported.user_id %>
</p>

<% if @sucess_contacts %>
  <h5>Success contacts created: </h5>
  <%= @sucess_contacts.count %>
  <br>
  <hr>
  <h5>Failed contacts</h5>
    <table class="table">
      <thead>
      <tr>
        <th>Name</th>
        <th>Birthdate</th>
        <th>Phone</th>
        <th>Address</th>
        <th>Credit card</th>
        <th>Franchise</th>
        <th>Email</th>
        <th>Error</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @failed_contacts.each_with_index do |contact, i| %>
        <tr>
          <td><%= contact.name %></td>
          <td><%= contact.birthdate %></td>
          <td><%= contact.phone %></td>
          <td><%= contact.address %></td>
          <td><%= contact.credit_card %></td>
          <td><%= contact.franchise %></td>
          <td><%= contact.email %></td>
          <td><%= @failed_contacts_msgs[i] %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>

<%= link_to 'Edit', edit_file_imported_path(@file_imported) %> |
<%= link_to 'Back', file_importeds_path %>